language: python
python:
 - 3.6
 - 3.7
before_install:
 - python --version
 - pip install -U pip
install:
 - pip install -e .
 - pip install flake8 pytest
script:
 - flake8 baruda test.py setup.py -v --show-source
 - pytest -v
